Spill Planning Method Updates
USGS-WiM/TravelTime pull request #308
Opened 2022-05-31 19:56 UTC by tgross-usgs

Changes include:

- Improved values for peak, leading edge, and trailing edge travel times
- Colorization based on most or max view in the map

To test travel time accuracy, run the application in two separate tabs. In the first tab, run the spill planning method, with a distance configuration of 10 at roughly 42.4418, -123.4959 which should capture Reach 23940647 as the downstream-most reach. Use the mean annual flow of nearest reach for the Discharge input in the Spill Planning modal and compute.
![image](https://user-images.githubusercontent.com/28792589/171270704-9cdd582f-bee0-48a9-ac0f-94561f4f7a95.png)
 In the resulting footer table, find reach 23930606. Highlight the row so you can easily view the leading edge, peak concentration, and trailing edge travel times. These represent the time it will take for a spill at the upstream Reach 23930606 to reach the downstream Reach 23940647. 

In the next tab, run the spill response method with a distance configuration of 6 at roughly 42.4320, -123.4046. The trace should begin with reach 23930606 and end downstream at Reach 23940647. 
![image](https://user-images.githubusercontent.com/28792589/171272745-dc825b85-f7b6-46cb-a6b3-68bd2026f141.png)
In the Spill Response modal type in a spill mass of 6000 and again, use the mean annual flow of the nearest reach for the Discharge input and compute. 
![image](https://user-images.githubusercontent.com/28792589/171270496-01acaa8c-4062-47b6-8d26-81b67f7a6d91.png)
The time of travel at the leading edge, peak, and trailing edge of Reach 23940647 should be similar to that of Reach 23930606 in your other browser tab where you ran the spill planning method. 
![image](https://user-images.githubusercontent.com/28792589/171272999-284bf89f-b2dc-4ccd-9a00-56c118eb4f38.png)

In case you're wondering why the difference in travel times... the formulas used for the spill planning and spill response workflow are different and will generate different values for velocity which create slight differences in travel times. In the spill response equations (downstream trace) formulas include slope. In the spill planning equations (upstream trace), formulas do not include slope and constants differ. 

You can run through these steps in the application that's currently live at https://streamstats.usgs.gov/tot-beta/ to see the change in values and how the travel times in the spill planning method now match up better. *if you want ;-)

2022-06-03 14:11 UTC, harper-wavra requested changes
When I ran the Spill Planning method, with a distance configuration of 10 at roughly 42.4418, -123.4959 I was seeing errors in the console and no plots in the footer. I am guessing the error 'Cannot read properties of undefined (reading 'datasets')', which I saw clicking on both plots is why there are no plots. I also saw 'Cannot read properties of undefined (reading 'layerPointToLatLng')' error when clicking on Most Probable. 

[Spill Planning](https://user-images.githubusercontent.com/59063181/171869784-21e1b682-21cd-48e7-8ca6-a8dab83ccb7f.png)
[Max Probable Console Errors](https://user-images.githubusercontent.com/59063181/171870042-6858066d-dbf5-4ee7-afeb-ab4250e43a4b.png)
[Most Probable Console Errors](https://user-images.githubusercontent.com/59063181/171870137-5c80d2b7-dcf3-4ce5-89ab-5fe22c627582.png)


When I ran Spill Response, with a spill mass of 6000 at roughly 42.4418, -123.4959, I was seeing similar errors ( 'Cannot read properties of undefined (reading 'layerPointToLatLng') with the Most Probable plot as I was seeing with Spill Planning. However, both plots are showing up. 
[Spill Response](https://user-images.githubusercontent.com/59063181/171869841-c9fc5775-f017-40db-b619-757a90e670d1.png)

2022-06-03 14:11 UTC, harper-wavra commented on dist/assets/data/secrets.json
> +{
We should add this file to the .gitignore so the token is not pushed up into the repo in the future. Once that is done I can add these to our secrets file on SharePoint so don't get lost/forgotten.

2022-06-03 14:11 UTC, harper-wavra commented on src/assets/data/secrets.json
> +{
Should add this file to gitignore as well.

2022-06-03 14:11 UTC, harper-wavra commented on src/app/components/help/help.component.html
> +<div class="modal-wrapper">
It looks like you added code for a help modal so users can submit a freshdesk ticket, but I wasn't able to find where to access the help modal on the webpage.

2022-06-03 14:17 UTC, harper-wavra commented
I got a new computer and had to re-clone this repository and was having difficulties with `npm install`. I was getting the error 'git@github.com: Permission denied (publickey)' when trying to ssh to the usgs/search_api. I solved it by changing this [line](https://github.com/USGS-WiM/TravelTime/blob/TAG-spillPlanning/package-lock.json#L13672), to "**https:**//git@github.com/usgs/search_api.git#a9537dd5549fd1149737dd2815b1146aa0a2bc01". We had a similar problem in the [SS-National application]( https://github.com/USGS-WiM/StreamStats-National/pull/123/commits/316a3ffa356216ad55301992912882630ab17a63), so just something to look out for in the future.

2022-06-06 17:22 UTC, tgross-usgs commented on src/app/components/help/help.component.html
> +<div class="modal-wrapper">
This was never fully implemented and must have been brought in from another of my branches.

2022-06-06 17:23 UTC, tgross-usgs commented on src/assets/data/secrets.json
> +{
Perhaps you can tell me which section of the gitignore file to put the secrets. It's been probably years since I've done this.

2022-06-06 17:29 UTC, tgross-usgs commented
The console errors for  'Cannot read properties of undefined (reading 'layerPointToLatLng') are expected and are present in the working version of ToT in beta. Everything appears to be represented in the map so it hasn't been a major issue, just clutter in the console. I did try looking into a fix this morning but I'm out of time and need to push this through. 

Also, we only have a chart in the footer for the Spill Response method. The fact that you didn't see it when running the Spill Planning method is expected. It is also why you see the error in the console for Spill Planning. There just isn't anything to show. Further cleanup will have to take place in the future.

2022-06-06 17:31 UTC, harper-wavra commented on src/assets/data/secrets.json
> +{
In streamstats we just added it to the bottom of the file: https://github.com/USGS-WiM/StreamStats/blob/dev/.gitignore#L165. I think its fine to put it anywhere inside the file.

2022-06-06 18:09 UTC, harper-wavra approved these changes

2022-06-06 18:09 UTC, merged